# Site settings
title: Byanka Cavalcante
email: byanka.byankasantos@gmail.com
url: https://cavalcantebya.github.io
description: "Digital game programming student through the IFRN-CM, carioca and 18 years old."
keywords: "digital games, design, audio, programming, c++"
skills: "Developer Student - Graphic Student - Game Programming"
meta_author: Cavalcante Byanka

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: CA7AFF #CC80FF
  primary-rgb: “204,102,255” #”204.128.255” 
  secondary: 4F2B4F  #986DFD
  secondary-dark: 3F223E #8412A1

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: IFRN- Ceará-Mirim
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/aknayb_
  - title: facebook
    url: https://www.facebook.com/byanka.cavalcante
  - title: instagram
    url: https://www.instagram.com/byanka_c/
  - title: tumblr
    url: http://you-in-my-crazy-world.tumblr.com/
 

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
<style type="text/css">body, a:hover {cursor: url(http://cur.cursors-4u.net/mechanics/mec-5/mec467.cur), progress !important;}</style><a href="http://www.cursors-4u.com/cursor/2011/11/30/sony-psp-2.html" target="_blank" title="Sony PSP"><img src="http://cur.cursors-4u.net/cursor.png" border="0" alt="Sony PSP" style="position:absolute; top: 0px; right: 0px;" /></a>

