{
	"version": 1510204550,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/background-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/nome-sheet0.png",
		"images/playb-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/créditosb-sheet0.png",
		"images/questionsb-sheet0.png",
		"images/loja-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/ceu-sheet0.png",
		"images/ceu-sheet1.png",
		"images/brasilia-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/bandeira-sheet0.png",
		"images/monney-sheet0.png",
		"images/constituição-sheet0.png",
		"images/chao1-sheet0.png",
		"images/chao2-sheet0.png",
		"images/chao3-sheet0.png",
		"images/personagem-sheet0.png",
		"images/spritefont.png",
		"images/tumulo-sheet0.png",
		"images/chao5-sheet0.png",
		"images/chao6-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/sprite17-sheet0.png",
		"media/boom sound effect.m4a",
		"media/boom sound effect.ogg",
		"media/vem pra rua instrumental.m4a",
		"media/vem pra rua instrumental.ogg",
		"media/que país é esse - legião urbana - karaokê (mp3cut.net).m4a",
		"media/que país é esse - legião urbana - karaokê (mp3cut.net).ogg",
		"media/vaia.m4a",
		"media/vaia.ogg",
		"media/h.m4a",
		"media/h.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}